version: '3'
services:
    zk1:
        image: "${REGISTRY}wurstmeister/zookeeper:${ZK_TAG:-latest}"
        ports:
            - "2181:2181"
            - "2888:2888"
            - "3888:3888"
        networks:
            - kafka-net
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_INIT_LIMIT: 5
            ZOOKEEPER_SYNC_LIMIT: 2
            ZOOKEEPER_SERVERS: zk1:2888:3888
        volumes:
          - ./zk-multiple-kafka-multiple/zk1/data:/data
          - ./zk-multiple-kafka-multiple/zk1/datalog:/datalog

    kafka1:
        deploy:
            mode: global
        image: "${REGISTRY}wurstmeister/kafka:${KAFKA_TAG:-latest}"
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ZOOKEEPER_CONNECT: zk1:2181
          KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
        networks:
          - kafka-net
        ports:
          - 9092:9092
        volumes:
          - ./zk-multiple-kafka-multiple/kafka1/data:/var/lib/kafka/data

    kafka2:
      deploy:
        mode: global
      image: "${REGISTRY}wurstmeister/kafka:${KAFKA_TAG:-latest}"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_LISTENERS: PLAINTEXT://:9093
        KAFKA_ZOOKEEPER_CONNECT: zk1:2181
        KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
      networks:
        - kafka-net
      ports:
        - 9093:9092
      volumes:
        - ./zk-multiple-kafka-multiple/kafka2/data:/var/lib/kafka/data

    kafka3:
      deploy:
        mode: global
      image: "${REGISTRY}wurstmeister/kafka:${KAFKA_TAG:-latest}"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: localhost
        KAFKA_LISTENERS: PLAINTEXT://:9093
        KAFKA_ZOOKEEPER_CONNECT: zk1:2181
        KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
      networks:
        - kafka-net
      ports:
        - 9094:9092
      volumes:
        - ./zk-multiple-kafka-multiple/kafka3/data:/var/lib/kafka/data

networks:
    kafka-net: